apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: test-secret
  namespace: sealed-secrets
spec:
  encryptedData:
    foo: AgABVf+bkPzsGHo7JZ/HV3EEYoRg2SYqTsC2QhgQG+wDPxXAU03hRQ7kDxHYQFCifaOabJX8gfCZsUhNIehh6fplC6+NZ05g00bRftuMoI5kKnYmoIAQ5SjP0Pf0ELd7qWizoj8Wmyup6Jk64sTqnsBO1E6XWAe1ghCPDbk8KAaTY98FhQpHLrY/SFxGRuKV67C4VrAU8vc81LnQA/oZ23P9YlClclCta4SW4E+Lc8og6cBnDmQ44Np7VowSRzUWmlp7KUDeyLUxcQ5LJvb96VZfpzZCdz0LvPn/0fcS63OYwG58tA9rRsYS2Sf2lE5NcfxnkrTIsasbEt94UEVkmP8QNBWCv0HFMPqj5X8VU+NTt7mO3vcnSj8ofMm+t8wwIpBR3ThNhb6yF1hHf2Jz9VHsG3nISKTiaC80voduwUtRAMs/VLhJ5NUSkfmxcrSx6qn1uZvqXNMlSjkYSQWc5wZN0HA294rL2aqfemtGYnESTO13VSPm4zgoxlughtO5Cfr6z81ERk44zYWSG2B2zO16VQSzUKWBgPrmdWE5w03G8KLxi3g/kQojp5yZJ5x1HSllmHzlh1ABEoWICbiMUEnaruZzXXxTYuRIaiSelTSRDaWQUwkPQ3aIVNa/2i9I15ZvvB8UuKhbrAUjU08kB0pD78bZuLIVBimUk6HwhiwQ3p0EUn4WG1wfJLYJfmCP2mSRmMk=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: test-secret
      namespace: sealed-secrets
    type: Opaque
