kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: open-cluster-management
resources:
  - ./namespace.yaml
  - ./operator-group.yaml
  - ./subscription.yaml
  - ./ns-admin.yaml
