apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rhacm-ns-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-nsadmin: "true"
rules:
  - apiGroups:
      - apps.open-cluster-management.io
    resources:
      - subscriptions
      - subscriptionstatuses
      - deployables
      - helmreleases
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy.open-cluster-management.io
    resources:
      - configurationpolicies
      - certificatepolicies
      - iampolicies
      - policies
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - observability.open-cluster-management.io
    resources:
      - observabilityaddons
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - agent.open-cluster-management.io
    resources:
      - certpolicycontrollers
      - applicationmanagers
      - workmanagers
      - searchcollectors
      - policycontrollers
      - iampolicycontrollers
    verbs:
      - get
      - list
      - watch
