#
# NonProd StorageClass.
#
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nutanix-files
  namespace: ntnx-system
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi.nutanix.com
parameters:
  dynamicProv: ENABLED
  nfsServerName: MELDVDINTXFS1 # nfsServerName is File Server Name in Prism without DNS suffix, not the FQDN.
  nfsPath: /openshift-meld-test-ccs-01
  csi.storage.k8s.io/provisioner-secret-name: nutanix-secret-meld
  csi.storage.k8s.io/provisioner-secret-namespace: ntnx-system
  storageType: NutanixFiles
reclaimPolicy: Delete