apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../base/1-operator
namespace: open-cluster-management
patchesJson6902:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: advanced-cluster-management
      namespace: open-cluster-management
    path: patch-channel-and-version.yaml