#
# Grant cluster-admin to cpm specific users.
#
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cpm-aad-cluster-admins
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: GBL All OpenShift EquatePlus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---  
#
# Grant cluster-reader to cpm specific users.
#
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cpm-aad-cluster-readers
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'GBL ALL OpenShift EquatePlus View (Universal)'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader 