kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: sealed-secrets-controller
  namespace: sealed-secrets
spec:
  to:
    kind: Service
    name: sealed-secrets-controller
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None