apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: dell-csi-operator
  namespace: isilon
  labels:
    app: dell-csi-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: dell-csi-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  

