kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wata_dev_cluster_admins
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: wata_dev_cluster_admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
