apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: | #Change the below Items
    type: s3
    config:
      bucket:
      endpoint: storage.googleapis.com
      insecure: false
      access_key:
      secret_key:
