kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ccs-aad-cluster-readers
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'GBL CCS OpenShift UK Prod Cluster View (Universal)'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
