apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
#  - ../../../base/3-observability
#namespace: rhacs-operator
resources:
  - mco.yaml
  - object-storage-secret.yaml
  - ocm-ob-namespace.yaml
  - custom-metrics-allowlist.yaml 
  - cluster-useable-capacity.yaml
  - load-average-drilldown.yaml
