apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Because MultiClusterHub needs to be updated by two different apps
# this has been moved to Policy configure-multi-cluster-hub.
# sjd 7 June 2022
#- multi-cluster-hub.yaml
- namespace.yaml
- operator-group.yaml
- oadp-operator.yaml
- data-protection-application.yaml
- backup-schedule.yaml
# Deliberate omission - requires manual configuration
#- secret-template.yaml
