apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-adp
  namespace: openshift-adp
  labels:
    app: oadp-operator
spec:
  targetNamespaces:
  - openshift-adp
