#
# Template Secret for holding ECS S3 credentials.
# Steps:
#   1 - Open in a text editor
#   2 - Replace the <FIXUP> sections below
#   3 - Create the Secret on the ACM local-cluster (hub) in 
#       namespace managed-secrets-channel-acm-ns.
#
# A namespace Subscription will replicate the Secret into NS openshift-adp.
#
apiVersion: v1
kind: Secret
metadata:
  name: ecs-s3-backup-credentials
  namespace: managed-secrets-channel-acm-ns
  labels:
    app: oadp-operator
  annotations:
    apps.open-cluster-management.io/deployables: secret
    secretname: ecs-s3-backup-credentials
stringData:
  cloud: |
    [default]
    aws_access_key_id=<FIXUP>
    aws_secret_access_key=<FIXUP>
type: Opaque
