apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patchesJson6902:
- target:
    group: apps.open-cluster-management.io
    version: v1
    kind: Subscription
    name: template-subscription
  patch: |-
    # Rename to prevent name clashes with other cluster deployments
    - op: replace
      path: /metadata/name
      value: helm-CLUSTER
    #
    - op: add
      path: /spec/packageOverrides/0/packageOverrides/0/value/nsIP
      value: 10.x.x.x
    #
    - op: add
      path: /spec/packageOverrides/0/packageOverrides/0/value/nsVIP
      value: 10.x.x.x
    #
    - op: add
      path: /spec/packageOverrides/0/packageOverrides/0/value/nsSNIPS
      value: '["10.x.x.x"]'
    #
    - op: replace
      path: /spec/placement/placementRef/name
      value: helm-CLUSTER

- target:
    group: apps.open-cluster-management.io
    version: v1
    kind: PlacementRule
    name: template-placement-rule
  patch: |-
    # Rename to prevent name clashes with other cluster deployments
    - op: replace
      path: /metadata/name
      value: helm-CLUSTER
    #
    - op: replace
      path: /spec/clusterSelector/matchLabels/name
      value: CLUSTER
