#
# Grant cluster-admin to gldev specific users.
#
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gldev-aad-cluster-admins
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'GBL All Openshift Global DEV Admins'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
#
# Grant cluster-reader to gldev specific users.
#
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gldev-aad-cluster-readers
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'GBL All OpenShift Global Development'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
