kind: Namespace
apiVersion: v1
metadata:
  name: rhacm-bootstrap-delete-me
  labels:
    deleteme: "true"
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rhacm-bootstrap-sa
  namespace: rhacm-bootstrap-delete-me
---
kind: ClusterRoleBinding
apiVersion: authorization.openshift.io/v1
metadata:
  name: rhacm-bootstrap-delete-me
roleRef:
  kind: ClusterRole
  name: cluster-admin
subjects:
- namespace: rhacm-bootstrap-delete-me
  kind: ServiceAccount
  name: rhacm-bootstrap-sa
