apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-disallowed-roles
  namespace: caas-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: AC Access Control
    policy.open-cluster-management.io/controls: AC-6 Least Privilege
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: no-wildcard-verbs
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: high
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["*"]
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                rules:
                - apiGroups:
                  - '*'
                  resources:
                  - '*'
                  verbs:
                  - '*'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-disallowed-roles
  namespace: caas-policies
placementRef:
  name: placement-policy-disallowed-roles
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-disallowed-roles
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-disallowed-roles
  namespace: caas-policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift
