apiVersion: network.openshift.io/v1
kind: EgressNetworkPolicy
metadata:
  name: smoke-test
  namespace: smoke-test
spec:
  egress:
  - type: Deny
    to:
      cidrSelector: 0.0.0.0/0 # Block everything else not listed above
