apiVersion: v1
kind: Namespace
metadata:
  name: gitops-channel
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: rhacm-deployed-smoke-test
  namespace: gitops-channel
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - rhacm-deployed-smoke-test
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: rhacm-deployed-smoke-test-channel
  namespace: gitops-channel
spec:
  type: Git
  pathname: https://github.ford.com/TDEICHEL/rhacm-smoke-test-app.git
  secretRef:
    name: github-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: github-auth
  namespace: gitops-channel
data:
  user: dGRlaWNoZWw=
  accessToken:
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch:
    apps.open-cluster-management.io/git-path:
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: rhacm-deployed-smoke-test
  name: rhacm-deployed-smoke-test-subscription
  namespace: gitops-channel
spec:
  channel: gitops-channel/rhacm-deployed-smoke-test-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: rhacm-deployed-smoke-test-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: rhacm-deployed-smoke-test
  name: rhacm-deployed-smoke-test-placement
  namespace: gitops-channel
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'
