apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ldap-sync

resources:
- namespace.yaml
- service-account.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- config-map-ca.yaml
- config-map-syncer.yaml
- cron-job.yaml
