#
# GitOps equivalent of command:
# oc adm policy add-cluster-role-to-group open-cluster-management:managedclusterset:admin:cpm 'GBL All OpenShift EquatePlus'
#
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'open-cluster-management:managedclusterset:admin:cpm'
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: GBL All OpenShift EquatePlus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'open-cluster-management:managedclusterset:admin:cpm'
