apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: group-sync-operator

resources:
- namespace.yaml
- operator-group.yaml
- group-sync-operator.yaml
- group-sync.yaml
- bindings-global.yaml
