apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
- bindings-local.yaml

patches:
- path: patch-bindings-global.yaml
  target:
    kind: ClusterRoleBinding
    name: aad-cluster-admins
